language: python

install:
  - pip install pipenv
  - pipenv sync --dev
  - pip install -e .

jobs:
  include:
    - stage: Style and Docs
      script: make test-style test-docs
      python: "3.8"

    - stage: Functonal tests
      script: make test-python
      python: "3.8"
